Try to taint server resources on patch
stackhpc/caas-workstation pull request #29
Opened 2024-10-15 15:03 UTC by JohnGarbutt

2024-10-15 17:51 UTC, JohnGarbutt commented on roles/cluster_infra/tasks/main.yml
> +- name: Find terraform outputs, just to initi tofu state
We probably should extract all of this into something we can use more easily for other appliances.

2024-10-16 10:52 UTC, mkjpryor requested changes
I thought we said we were going to put this in the Terraform collection so it could easily be used elsewhere?

2024-10-17 10:14 UTC, JohnGarbutt commented
> I thought we said we were going to put this in the Terraform collection so it could easily be used elsewhere?

We are, but @assumptionsandg is going to look at doing that next :)

2024-11-01 17:27 UTC, mkjpryor commented
Superseded by #31

2024-11-01 17:27 UTC, closed without merging