Pass Azimuth update reason to the Infra role
stackhpc/caas-workstation pull request #31
Opened 2024-11-01 14:02 UTC by assumptionsandg

Pass Azimuth update reason to the Infra role to ensure rebuilds on patched appliances.

2024-11-01 17:24 UTC, mkjpryor requested changes

2024-11-01 17:24 UTC, mkjpryor commented on roles/cluster_infra/tasks/main.yml
> +    terraform_rebuild_nodes: "{{ azimuth_rebuild_platform | default(false) }}"
I don't think we need the `set_fact`.

If we set a role default as `azimuth_update_reason: reconfigure`, then this can just be:

```yaml
terraform_rebuild_nodes: "{{ azimuth_update_reason == 'patch' }}"
```

2024-11-04 08:09 UTC, mkjpryor commented
We should wait for the release of the Terraform collection that includes this and bump it in this PR.

2024-11-07 18:32 UTC, JohnGarbutt commented
Yeah +1 what mattp said here.

2024-11-11 11:10 UTC, mkjpryor commented
@assumptionsandg 

Can you update the Terraform collection to the 0.5.0 release and retest the patch? Thanks!

2024-11-12 11:27 UTC, holliefae commented
Tested

2024-11-12 11:36 UTC, mkjpryor approved these changes
LGTM

2024-11-12 11:36 UTC, merged